<template>
  <div>
    <b-row class="p-md-4 mx-md-4" cols="1" cols-md="2" align-content="center">
      <b-col xs="auto" sm="auto" md="12" lg="12">
        <h1 class="text-md-left text-center">Projects</h1>
        <hr />
        <p>
          Here are some of the projects I have completed. This page will be continuously updated as I complete new projects that I am working on. Currently, I am working on two
          different mobile apps using Flutter as well as a game created in the Godot engine.
        </p>
      </b-col>
    </b-row>

    <b-row class="px-md-4 pm-md-4 mx-md-4 mb-4" cols="1" cols-md="2" align-content="center">
      <b-col class="p-md-3 p-sm-1 d-flex align-items-stretch" v-for="(project, index) in allProjects" :key="index">
        <b-card-group deck>
          <b-card
            :title="project.title"
            :img-src="project.image"
            :img-alt="project.alt"
            img-top
            tag="article"
            class="p-2 shadow neumorphism"
          >
            <a :href="project.link" target="_blank" class="stretched-link"></a>
            <b-card-text>{{project.description}}</b-card-text>
          </b-card>
        </b-card-group>
      </b-col>
    </b-row>
  </div>
</template>

<script>
export default {
  name: "Projects",
  data() {
    return {
      allProjects: [
        {
          title: "RobCaporino.com",
          description:
            "View the source code for this single page website built with Vuejs here.",
          image: require("../assets/R.Caporino_logo_thumbnail.png"),
          alt: "Rob Caporino Logo",
          link: "https://github.com/rcaporino/mywebsite"
        },
        {
          title: "Sudoku Solver",
          description:
            "A web app where you can play sudoku and solve the puzzles yourself, or watch a recursive backtracking algorithm in action solve it!. You can control the speed at which the algorithm solves the puzzle and see each number it tries to put into the grid. Each sudoku was generated by me using a python script.",
          image: require("../assets/sudoku_preview.png"),
          alt: "Preview of Sudoku Solver",
          link: "https://rcaporino.github.io/sudoku-backtrack/"
        },
        {
          title: "Py Buddy",
          description:
            'A demo for a mobile game concept that would teach the user python. Each level consists of a lesson and a puzzle. For the puzzles the user will enter "code" into a console, based on what was taught in the lesson to solve the problem.',
          image: require("../assets/pybuddy_preview.png"),
          alt: "Preview of PyBuddy",
          link: "https://github.com/rcaporino/py-buddy"
        }
      ]
    };
  }
};
</script>

<style>
.card-img-top {
  width: 100%;
  height: 10vw;
  object-fit: cover;
}

article:hover {
  background: #efefef !important;
  box-shadow: -20px -20px 40px 0px rgba(255, 255, 255, 1),
    20px 20px 40px 1px rgba(0, 0, 0, 0.3) !important;
}

@media (max-width: 767px) {
  .card-img-top {
    width: 100%;
    height: 30vw;
    object-fit: cover;
  }
}
</style>